const http=require('http');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const os=require('os');
const ROOT=__dirname, PUBLIC=path.join(ROOT,'public'), STATE_FILE=process.env.GAME_STATE_FILE||path.join(ROOT,'game-state.json');
const game=JSON.parse(fs.readFileSync(path.join(ROOT,'game-data.json'),'utf8'));
const allowedGroups=['A','B','C','D','V'];
const MIN_GROUP_SIZE=2,MIN_ATTENDEES=allowedGroups.length*MIN_GROUP_SIZE;
const MINUTE=Math.max(1,Number(process.env.GAME_MINUTE_MS||60000));
const PORT=Math.max(1,Number(process.env.PORT||8764));
const DEADLINES={base:90*MINUTE,v:120*MINUTE,e:210*MINUTE,total:300*MINUTE};
const HINT_MARKS={A:[30,55,80],B:[30,55,80],C:[30,55,80],D:[30,55,80],V:[95,105,115],E:[145,175,200]};
const HINTS={
 A:['Prüft jeden Eintrag wie einen eigenen Fall: Löst die beschriebene Identität eine konkrete Reaktion im System aus?','Ein Name oder bloße Sichtbarkeit genügt nicht. Achtet auf Handlung, Zahlung, Prüfung oder eine andere nachweisbare Wirkung.','Zählt die Einträge mit kausal wirksamer Person oder Rolle. Ein rein sichtbares, aber folgenloses Profil fällt aus der Wertung.'],
 B:['Sammelt zunächst alle genannten Orte und markiert, ob dort etwas überprüft, ausgezahlt oder tatsächlich ausgelöst wurde.','Wiederholung allein macht einen Ort nicht relevant. Gesucht sind unterschiedliche Orte, die vom Hintergrund zur Bühne einer Handlung werden.','Zählt jeden wirksamen Ort nur einmal. Reine Verteiler-, Tarn- und Kulissenorte werden gestrichen.'],
 C:['Legt die Einträge nach ihren Jahreszahlen aus und trennt bloße Erinnerung von einem belegten Vorgang.','Ein Jahr zählt nur, wenn darin eine erkennbare Bewegung, Entscheidung oder Wirkung beschrieben wird. Leere Zeitfenster bleiben außen vor.','Markiert alle Jahre mit einem tatsächlich wirksamen Ereignis und zählt die unterschiedlichen markierten Jahre.'],
 D:['Erstellt pro Eintrag eine einfache Kette: Ausgang, tatsächlicher Geldfluss, Ziel und belastbarer Nachweis.','Erwähnte Beträge, vorgesehene Zahlungen und unklare Kontoeingänge sind noch keine bestätigten Transaktionen.','Zählt nur die Fälle, deren Geldfluss ausdrücklich real und in seiner Wirkung eindeutig beschrieben ist.'],
 V:['Vier Regeln wirken plausibel, aber nur zwei tragen. Prüft die Aussagen gegen die vier übermittelten Gruppenziffern.','Eine tragfähige Regel verändert die Mitte; die andere verändert jede Ziffer mit einem zyklischen Überlauf nach 9.','Tauscht zuerst Position zwei und drei. Addiert danach zu jeder Ziffer zwei; nach 9 beginnt die Zählung wieder bei 0.'],
 E:['Übersetzt jede Aussage in eine Positionsbedingung und ordnet jeder Ziffer genau einen Platz zu.','Fixiert die direkten Aussagen: Die Sechs eröffnet, die Null steht an dritter Stelle und OceanMan-37 schließt die Reihe. Für die Vier bleibt damit nur ein Platz.','Prüft die aus V erhaltene Folge als Ausgangspunkt. Das wahre Ende führt zurück: Die konsistente Reihenfolge lautet 64-07.']
};
let state={sessions:{},claimed:{},solved:{A:null,B:null,C:null,D:null},solvedSource:{},complete:false,startedAt:null};
if(fs.existsSync(STATE_FILE)){try{state=JSON.parse(fs.readFileSync(STATE_FILE,'utf8'))}catch{}}
state.sessions=state.sessions||{};state.claimed=state.claimed||{};state.solved=state.solved||{A:null,B:null,C:null,D:null};state.solvedSource=state.solvedSource||{};state.complete=Boolean(state.complete);state.vComplete=Boolean(state.vComplete);state.groupsLocked=Boolean(state.groupsLocked);state.startedAt=state.startedAt||null;
function save(){fs.writeFileSync(STATE_FILE,JSON.stringify(state,null,2),'utf8')}
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1))]}))}
function session(req,res){let sid=cookies(req).sid;if(!sid||!state.sessions[sid]){sid=crypto.randomBytes(16).toString('hex');state.sessions[sid]={intro:false,group:null,audioDone:false,unlocked:false,attempts:[],lockedUntil:0,vPassed:false,eAudioDone:false,eUnlocked:false,finalComplete:false,username:null};state.sessions[sid].created=Date.now();res.setHeader('Set-Cookie',`sid=${sid}; Path=/; Max-Age=259200; SameSite=Lax`);save()}state.sessions[sid].lastSeen=Date.now();return [sid,state.sessions[sid]]}
function send(res,status,obj){const body=JSON.stringify(obj);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(body)}
function body(req){return new Promise((resolve,reject)=>{let d='';req.on('data',c=>{d+=c;if(d.length>100000)reject(new Error('large'))});req.on('end',()=>{try{resolve(d?JSON.parse(d):{})}catch(e){reject(e)}})})}
function norm(v){return String(v||'').trim().toLocaleLowerCase('de-DE').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ')}
function markerPositions(text,solution){const wanted=solution.replace(/\s/g,'').split('');let selected=[],min=0;for(let i=0;i<wanted.length;i++){const target=Math.floor((i+1)*text.length/(wanted.length+1));let best=-1,dist=Infinity;for(let p=min;p<text.length;p++){if(text[p].toLocaleUpperCase('de-DE')===wanted[i].toLocaleUpperCase('de-DE')){const d=Math.abs(p-target);if(d<dist){best=p;dist=d}if(p>target&&d>dist)break}}if(best>=0){selected.push(best);min=best+1}}return selected}
function elapsedMs(){return state.startedAt?Math.max(0,Date.now()-state.startedAt):0}
function isLocal(req){const address=req.socket.remoteAddress||'';return address==='127.0.0.1'||address==='::1'||address==='::ffff:127.0.0.1'}
function attendance(){const now=Date.now();const people=Object.values(state.sessions).filter(s=>s.username).map(s=>({username:s.username,joinedAt:s.joinedAt||s.created,online:now-(s.lastSeen||0)<20000,group:s.group||null})).sort((a,b)=>a.joinedAt-b.joinedAt);return {people,online:people.filter(p=>p.online).length,total:people.length}}
function groupCounts(){const counts=Object.fromEntries(allowedGroups.map(g=>[g,0]));for(const s of Object.values(state.sessions))if(s.group&&counts[s.group]!==undefined&&(state.groupsLocked||Date.now()-(s.lastSeen||0)<20000))counts[s.group]++;return counts}
function groupsReady(counts=groupCounts()){const everyoneAssigned=attendance().people.filter(p=>p.online).every(p=>p.group);return everyoneAssigned&&allowedGroups.every(g=>counts[g]>=MIN_GROUP_SIZE)}
function baseIntervention(s){return Boolean(s.group&&['A','B','C','D'].includes(s.group)&&state.solvedSource[s.group]==='external'&&!s.baseInterventionSeen)}
function enforce(s){if(!state.startedAt)return;const elapsed=elapsedMs();let changed=false;if(elapsed>=DEADLINES.base){for(const g of ['A','B','C','D'])if(state.solved[g]===null){state.solved[g]=game.groups[g].answer;state.solvedSource[g]='external';changed=true}if(s.group&&['A','B','C','D'].includes(s.group)&&state.solvedSource[s.group]==='external'&&(!s.audioDone||!s.unlocked)){s.audioDone=true;s.unlocked=true;changed=true}}if(s.group==='V'&&elapsed>=DEADLINES.v&&!state.vComplete){if(!s.audioDone||!s.unlocked||s.intervention!=='V')changed=true;s.audioDone=true;s.unlocked=true;s.intervention='V'}if(s.group==='V'&&state.vComplete&&elapsed>=DEADLINES.e&&!state.complete){if(!s.eAudioDone||!s.eUnlocked||s.intervention!=='E')changed=true;s.eAudioDone=true;s.eUnlocked=true;s.intervention='E'}if(changed)save()}
function snapshot(s){enforce(s);const now=Date.now(),present=attendance(),counts=groupCounts();return {running:Boolean(state.startedAt),registered:Boolean(s.username),username:s.username||null,attendeeCount:present.online,minAttendees:MIN_ATTENDEES,introSolved:s.intro,group:s.group,groupCounts:counts,groupsReady:groupsReady(counts),groupsLocked:state.groupsLocked,audioDone:s.audioDone,unlocked:s.unlocked,keywordLength:s.group?game.groups[s.group].keyword.length:null,eKeywordLength:state.vComplete?game.groups.E.keyword.length:null,groupSolved:s.group&&s.group!=='V'?state.solved[s.group]!==null:false,groupSolvedSource:s.group?state.solvedSource[s.group]||null:null,vPassed:state.vComplete,eAudioDone:s.eAudioDone,eUnlocked:s.eUnlocked,finalComplete:Boolean(s.finalComplete||state.complete),lockedRemaining:Math.max(0,s.lockedUntil-now),allBaseSolved:['A','B','C','D'].every(g=>state.solved[g]!==null),serverNow:now,startedAt:state.startedAt,deadlines:DEADLINES,intervention:s.intervention||(baseIntervention(s)?'BASE':null)}}
function checkRate(s){const now=Date.now();if(s.lockedUntil>now)return {locked:true,remaining:s.lockedUntil-now};s.attempts=(s.attempts||[]).filter(t=>now-t<300000);return {locked:false}}
function wrong(s){const now=Date.now();s.attempts=(s.attempts||[]).filter(t=>now-t<300000);s.attempts.push(now);if(s.attempts.length>=3){s.lockedUntil=now+600000;s.attempts=[]}save();return Math.max(0,s.lockedUntil-now)}
function publicState(s){enforce(s);return {solved:state.solved,solvedSource:state.solvedSource,allBaseSolved:['A','B','C','D'].every(g=>state.solved[g]!==null)}}

async function api(req,res,pathname){const [sid,s]=session(req,res);let data={};if(req.method==='POST'){try{data=await body(req)}catch{return send(res,400,{error:'Ungültige Anfrage'})}}
 if(req.method==='GET'&&pathname==='/api/admin/status'){if(!isLocal(req))return send(res,403,{error:'Nur auf dem Spielleitungsrechner verfügbar'});const present=attendance();return send(res,200,{running:Boolean(state.startedAt),startedAt:state.startedAt,serverNow:Date.now(),total:DEADLINES.total,minAttendees:MIN_ATTENDEES,minGroupSize:MIN_GROUP_SIZE,attendees:present.people,onlineCount:present.online,registeredCount:present.total,groupCounts:groupCounts(),groupsLocked:state.groupsLocked,solved:state.solved,solvedSource:state.solvedSource,complete:state.complete})}
 if(req.method==='POST'&&pathname==='/api/admin/start'){if(!isLocal(req))return send(res,403,{error:'Nur auf dem Spielleitungsrechner verfügbar'});const online=attendance().online;if(online<MIN_ATTENDEES)return send(res,409,{error:`Mindestens ${MIN_ATTENDEES} anwesende Personen werden benötigt – aktuell ${online}`});if(!state.startedAt){state.startedAt=Date.now();save()}return send(res,200,{ok:true,running:true,startedAt:state.startedAt,serverNow:Date.now(),total:DEADLINES.total})}
 if(req.method==='GET'&&pathname==='/api/session')return send(res,200,snapshot(s));
 if(req.method==='POST'&&pathname==='/api/lobby/join'){if(state.groupsLocked&&!s.username)return send(res,409,{error:'Die Gruppenphase ist bereits abgeschlossen'});const username=String(data.username||'').trim().replace(/\s+/g,' ');if(username.length<2||username.length>30||/[<>\x00-\x1f]/.test(username))return send(res,400,{error:'Der Username muss aus 2 bis 30 zulässigen Zeichen bestehen'});if(s.username&&norm(s.username)!==norm(username))return send(res,409,{error:'Für dieses Gerät wurde bereits ein Username festgelegt'});const duplicate=Object.values(state.sessions).find(other=>other!==s&&other.username&&norm(other.username)===norm(username)&&Date.now()-(other.lastSeen||0)<120000);if(duplicate)return send(res,409,{error:'Dieser Username ist bereits in der Lobby anwesend'});s.username=username;s.joinedAt=s.joinedAt||Date.now();s.lastSeen=Date.now();save();return send(res,200,{ok:true,state:snapshot(s)})}
 if(!s.username)return send(res,403,{error:'Bitte zuerst mit einem Username in der Lobby anmelden'});
 if(!state.startedAt)return send(res,409,{error:'Die Spielleitung hat das Spiel noch nicht gestartet'});
 if(req.method==='GET'&&pathname==='/api/article')return send(res,200,{transcript:game.articleTranscript,markerPositions:markerPositions(game.articleTranscript,game.introAnswer),images:['media/article-final-subtil-1.png','media/article-final-subtil-2.png'],version:'artikel-final-subtil-2160'});
 if(req.method==='GET'&&pathname==='/api/public-state'){if(s.group!=='V')return send(res,403,{error:'Nur für die zentrale Validierung verfügbar'});return send(res,200,publicState(s))}
 if(req.method==='GET'&&pathname==='/api/hints'){enforce(s);const stage=new URL(req.url,'http://x').searchParams.get('stage')==='E'?'E':s.group;if(!stage||!HINTS[stage])return send(res,400,{error:'Keine Hinweisphase'});const opened=stage==='E'?s.eArchiveOpenedAt:s.archiveOpenedAt;if(!opened)return send(res,403,{error:'Archiv noch nicht geöffnet'});const marks=HINT_MARKS[stage];const age=elapsedMs();const available=state.startedAt?marks.filter(m=>age>=m*MINUTE).length:0;return send(res,200,{stage,hints:HINTS[stage].slice(0,available),nextIn:available<3&&state.startedAt?Math.max(0,marks[available]*MINUTE-age):0,total:3})}
 if(req.method==='GET'&&pathname==='/api/final'){if(!state.complete&&!s.finalComplete)return send(res,403,{error:'Finale nicht freigegeben'});return send(res,200,{audio:'media/Abschlussbrief.mp3',transcript:game.finalTranscript})}
 if(req.method==='GET'&&pathname==='/api/recovery'){enforce(s);const stage=baseIntervention(s)?'BASE':s.intervention;if(stage==='BASE')return send(res,200,{stage,displayAnswer:game.groups[s.group].answer,note:'Ein kausal belastbares Merkmal wurde in den geöffneten Akten rot isoliert. Die Segmentzahl ist aus dem rekonstruierten Muster wiederhergestellt.'});if(stage==='V'&&s.group==='V')return send(res,200,{stage,displayAnswer:game.groups.V.answer,note:'Zwei tragfähige Operationen isoliert: MITTE TAUSCHEN → +2 MIT ÜBERLAUF.'});if(stage==='E'&&s.group==='V')return send(res,200,{stage,displayAnswer:`${game.groups.E.answer.slice(0,2)}-${game.groups.E.answer.slice(2)}`,note:'Das wahre Ende führt zurück. Die konsistente Signatur wurde aus den Positionsfragmenten rekonstruiert.'});return send(res,403,{error:'Kein externer Eingriff autorisiert'})}
 if(req.method==='POST'&&pathname==='/api/intro'){if(norm(data.answer)!==norm(game.introAnswer))return send(res,403,{ok:false,error:'Lösungswort nicht korrekt'});s.intro=true;save();return send(res,200,{ok:true})}
 if(req.method==='POST'&&pathname==='/api/select'){const g=String(data.group||'').toUpperCase();if(!s.intro)return send(res,403,{error:'Einführungsrätsel noch nicht gelöst'});if(!allowedGroups.includes(g))return send(res,400,{error:'Unbekannte Gruppe'});if(state.groupsLocked&&s.group!==g)return send(res,409,{error:'Die Gruppen wurden bereits verbindlich gesperrt'});s.group=g;const counts=groupCounts();if(groupsReady(counts))state.groupsLocked=true;save();return send(res,200,{ok:true,state:snapshot(s)})}
 if(!state.groupsLocked)return send(res,409,{error:`Alle Gruppen benötigen mindestens ${MIN_GROUP_SIZE} anwesende Personen`});
 if(req.method==='POST'&&pathname==='/api/audio-ended'){if(!s.group)return send(res,403,{error:'Keine Gruppe'});if(data.stage==='E'){if(!state.vComplete)return send(res,403,{error:'E-Phase nicht freigegeben'});s.eAudioDone=true}else{s.audioDone=true}save();return send(res,200,{ok:true})}
 if(req.method==='POST'&&pathname==='/api/key'){if(!s.group)return send(res,403,{error:'Keine Gruppe'});const stage=data.stage==='E'?'E':s.group;if(stage==='E'){if(!state.vComplete||!s.eAudioDone)return send(res,403,{error:'E0 muss vollständig abgespielt werden'});if(norm(data.keyword)!==norm(game.groups.E.keyword))return send(res,403,{error:'Zugriffsschlüssel nicht korrekt'});s.eUnlocked=true;s.eArchiveOpenedAt=s.eArchiveOpenedAt||Date.now()}else{if(!s.audioDone)return send(res,403,{error:`${s.group}.0 muss vollständig abgespielt werden`});if(norm(data.keyword)!==norm(game.groups[s.group].keyword))return send(res,403,{error:'Zugriffsschlüssel nicht korrekt'});s.unlocked=true;s.archiveOpenedAt=s.archiveOpenedAt||Date.now()}save();return send(res,200,{ok:true})}
 if(req.method==='GET'&&pathname==='/api/content'){enforce(s);const stage=new URL(req.url,'http://x').searchParams.get('stage')==='E'?'E':s.group;if(stage==='E'&&!s.eUnlocked)return send(res,403,{error:'E-Archiv gesperrt'});if(stage!=='E'&&!s.unlocked)return send(res,403,{error:'Gruppenarchiv gesperrt'});if(stage==='E')s.eArchiveOpenedAt=s.eArchiveOpenedAt||Date.now();else s.archiveOpenedAt=s.archiveOpenedAt||Date.now();save();const pageCounts={A:5,B:5,C:4,D:6,E:10,V:6};return send(res,200,{group:stage,articleImages:['media/article-final-subtil-1.png','media/article-final-subtil-2.png'],documentPages:Array.from({length:pageCounts[stage]},(_,i)=>`media/diaries/${stage}/${stage}-${i+1}.png`),originalPdf:game.groups[stage].originalPdf})}
 if(req.method==='POST'&&pathname==='/api/force'){enforce(s);if(baseIntervention(s)&&data.stage==='BASE'){s.baseInterventionSeen=true;save();return send(res,200,{ok:true,state:snapshot(s)})}if(s.intervention==='V'&&s.group==='V'){state.vComplete=true;s.intervention=null;save();return send(res,200,{ok:true,state:snapshot(s)})}if(s.intervention==='E'&&s.group==='V'){s.finalComplete=true;s.intervention=null;state.complete=true;save();return send(res,200,{ok:true,state:snapshot(s),finalTranscript:game.finalTranscript})}return send(res,403,{error:'Kein externer Eingriff autorisiert'})}
 if(req.method==='POST'&&pathname==='/api/answer'){if(!s.group)return send(res,403,{error:'Keine Gruppe'});const rate=checkRate(s);if(rate.locked)return send(res,429,{error:'Eingabe wegen wiederholter Fehlversuche gesperrt',lockedRemaining:rate.remaining});const stage=data.stage==='E'?'E':s.group;if(stage==='E'&&!s.eUnlocked)return send(res,403,{error:'E-Archiv gesperrt'});if(stage!=='E'&&!s.unlocked)return send(res,403,{error:'Archiv gesperrt'});if(stage==='V'&&!['A','B','C','D'].every(g=>state.solved[g]!==null))return send(res,409,{error:'Noch nicht alle Gruppenergebnisse A–D liegen vor'});const entered=String(data.answer||'').replace(/\s|-/g,'');const expected=game.groups[stage].answer;if(entered!==expected){const remaining=wrong(s);return send(res,remaining?429:403,{ok:false,error:remaining?'Zu viele Fehlversuche – Eingabe für 10 Minuten gesperrt':'Ergebnis nicht korrekt',lockedRemaining:remaining})}s.attempts=[];s.lockedUntil=0;if(['A','B','C','D'].includes(stage)){state.solved[stage]=expected;state.solvedSource[stage]='submitted'}else if(stage==='V'){state.vComplete=true}else{s.finalComplete=true;state.complete=true}save();return send(res,200,{ok:true,state:snapshot(s),finalAudio:stage==='E'?'media/Abschlussbrief.mp3':null,finalTranscript:stage==='E'?game.finalTranscript:null,eAudio:stage==='V'?game.groups.E.audio:null})}
 return send(res,404,{error:'Nicht gefunden'});
}
function staticFile(req,res,pathname){let rel=pathname==='/'?'index.html':decodeURIComponent(pathname.slice(1));let file=path.resolve(PUBLIC,rel);if(!file.startsWith(path.resolve(PUBLIC)))return res.writeHead(403).end();if(!fs.existsSync(file)||fs.statSync(file).isDirectory())return res.writeHead(404).end('Not found');const ext=path.extname(file).toLowerCase();const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.mp3':'audio/mpeg','.pdf':'application/pdf','.txt':'text/plain; charset=utf-8'};const fresh=['.html','.js','.css','.png'].includes(ext);res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':fresh?'no-store':'public, max-age=3600'});fs.createReadStream(file).pipe(res)}
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://x').pathname;if(pathname.startsWith('/api/'))api(req,res,pathname).catch(e=>send(res,500,{error:e.message}));else staticFile(req,res,pathname)});
server.on('error',error=>{if(error.code==='EADDRINUSE'){console.error(`\nPort ${PORT} wird bereits verwendet. Bitte die alte Spielserver-Instanz schließen und erneut starten.\n`);process.exit(1)}throw error});
server.listen(PORT,'0.0.0.0',()=>{console.log('\nL&B Spielinterface läuft.\n');console.log(`Spielleitung:       http://localhost:${PORT}/leitung.html`);console.log(`Auf diesem Rechner: http://localhost:${PORT}`);for(const list of Object.values(os.networkInterfaces()))for(const n of list||[])if(n.family==='IPv4'&&!n.internal)console.log(`Für Teilnehmende:  http://${n.address}:${PORT}`);console.log('\nDie Spieluhr startet erst über die Spielleitungsseite.\nFenster geöffnet lassen. Beenden mit Strg+C.\n')});
